---
title: "14.Veg_trt_by_plot"
author: "Colin Kirkmire"
date: "June 2, 2016"
output: word_document
---

Examining Relationship between init height and inc growth
```{r}
source('C:/Users/Colin/Desktop/R-Projects/INGY/11.Quant_reg_LL.r', echo=F)

overall_lm<-lm(LL_both$inc~LL_both$Height_Total.x)

summary(overall_lm)

overall_lm_curve<-lm(LL_both$inc~sqrt(LL_both$Height_Total.x))

summary(overall_lm_curve)
```
By treatment
```{r}
LL_GE<-LL_both[which(LL_both$Treatment=="GE"),]
LL_CTRL<-LL_both[which(LL_both$Treatment=="CTRL"),]
LL_X<-LL_both[which(LL_both$Treatment=="1X"),]
LL_GE_lm<-lm(LL_GE$inc~LL_GE$Height_Total.x)
LL_GE_lm_curve<-lm(LL_GE$inc~sqrt(LL_GE$Height_Total.x))
summary(LL_GE_lm)
summary(LL_GE_lm_curve)

LL_CTRL_lm<-lm(LL_CTRL$inc~LL_CTRL$Height_Total.x)
LL_CTRL_lm_curve<-lm(LL_CTRL$inc~sqrt(LL_CTRL$Height_Total.x))
summary(LL_CTRL_lm)
summary(LL_CTRL_lm_curve)
```
Curved relationship leads to lesser R2 for CTRL
```{r}
LL_X_lm<-lm(LL_X$inc~LL_X$Height_Total.x)
LL_X_lm_curve<-lm(LL_X$inc~sqrt(LL_X$Height_Total.x))
summary(LL_X_lm)
summary(LL_X_lm_curve)
```

Plotting Curved Relationships
```{r}
library(quantreg)

tau=c(.05,.25,.5,.75,.95)

sq_rq05<-rq(LL_both$inc~sqrt(LL_both$Height_Total.x), tau=.05)
sq_rq25<-rq(LL_both$inc~sqrt(LL_both$Height_Total.x), tau=.25)
sq_rq5<-rq(LL_both$inc~sqrt(LL_both$Height_Total.x), tau=.5)
sq_rq75<-rq(LL_both$inc~sqrt(LL_both$Height_Total.x), tau=.75)
sq_rq95<-rq(LL_both$inc~sqrt(LL_both$Height_Total.x), tau=.95)

plot(LL_both$Height_Total.x,LL_both$inc ,cex=.5,pch=19,xlab="Initial Height", ylab="Height Growth Increment",
     col=LL_both$Treatment)
#points(LL_both$Height_Total.x,LL_both$inc,cex=.8)
curve((sq_rq05$coefficients[2]*sqrt(x))+sq_rq05$coefficients[1], add = TRUE, col = "black")
curve((sq_rq25$coefficients[2]*sqrt(x))+sq_rq25$coefficients[1], add = TRUE, col = "black")
curve((sq_rq5$coefficients[2]*sqrt(x))+sq_rq5$coefficients[1], add = TRUE, col = "black")
curve((sq_rq75$coefficients[2]*sqrt(x))+sq_rq75$coefficients[1], add = TRUE, col = "black")
curve((sq_rq95$coefficients[2]*sqrt(x))+sq_rq95$coefficients[1], add = TRUE, col = "black")


```