Trying alternative rq (Interpolated growth curves)
```{r}

library(quantreg)

LL1<-merged_stagm_stag[merged_stagm_stag$Installation=="LL"&merged_stagm_stag$Species=="PIPO"&merged_stagm_stag$Plot%in%c(1:7)&merged_stagm_stag$Year_Measurement%in%c(2001,2004,2008),]




plot(LL1$Year_Measurement,LL1$Height_Total,cex=.5,pch=19,main="Total Height vs Year of Measurement",
     xlab="Year of Measurement", ylab="Total Height (ft)",
     col=LL_rLL$Installation)
points(LL1$Year_Measurement,LL1$Height_Total,cex=.8)
abline(rq(LL1$Height_Total~LL1$Year_Measurement, tau=.5), col="blue")
abline(lm(LL1$Height_Total~LL1$Year_Measurement,lty=2, col="red"))

taus<-c(.05,.1,.25,.50,.75,.9,.95)

for(i in 1:length(taus)){
  abline(rq(Height_Total~Year_Measurement,tau=taus[i],data=LL1),col="gray")
}

fit2<-summary(rq(LL_rLL$Height_Total~LL_rLL$Year_Measurement,tau=c(.05,.25,.5,.75,.95)))
fit2


```
What does the above look like on multiple dim?
```{r}
LL1<-merge(LL1,splot,by=c("Installation","Plot"))

LL1$veg<-with(LL1, ifelse(LL1$Treatment=="GE",LL_veg_2004$Coverage[LL_veg_2004$Treatment=="GE"],
                          ifelse(LL1$Treatment=="1X",LL_veg_2004$Coverage[LL_veg_2004$Treatment=="1X"],
                                 LL_veg_2004$Coverage[LL_veg_2004$Treatment=="CTRL"] )))


library(rgl)

plot3d(LL1$Year_Measurement, LL1$veg, LL1$Height_Total, 
       axes=FALSE,size=7,
       col="black",
       xlab="", ylab="", zlab="")
axes3d(c("x+", "y-", "z-"))
grid3d(side=c('x+', 'y-', 'z'), col="gray")
title3d(main="Loon Lake QR of Ht on % Vegetative VOlume and Year",
        ylab = "Veg Cover %",
        zlab = "Total Height (ft)",
        xlab = "Year Measurement",
        col="black",cex.main=2)

#Adding vertical droplines#
#plot3d(threeDVeg$SiteIndex_Value,threeDVeg$ave.BAPA,threeDVeg$volume,type='h',add=T,
#col=myColorRamp(c("blue","green","yellow","red"),threeDVeg$volume))

#Fitting&Plotting RQ Planes#

fit1=rq(LL1$Height_Total~LL1$Year_Measurement+LL1$veg+LL1$Year_Measurement:LL1$veg, tau=.2)
summary(fit1)

coefs <- coef(fit1)
planes3d(a=coefs["LL1$Year_Measurement"], b=coefs["LL1$veg"],-1, coefs["(Intercept)"], alpha=0.50, col="blue")

fit2=rq(LL1$Height_Total~LL1$Year_Measurement+LL1$veg, tau=.5)
summary(fit2)

coefs <- coef(fit2)
planes3d(a=coefs["LL1$Year_Measurement"], b=coefs["LL1$veg"],-1, coefs["(Intercept)"], alpha=0.50, col="red")

fit3=rq(LL1$Height_Total~LL1$Year_Measurement+LL1$veg, tau=.8)
summary(fit3)

coefs <- coef(fit3)
planes3d(a=coefs["LL1$Year_Measurement"], b=coefs["LL1$veg"],-1, coefs["(Intercept)"], alpha=0.50, col="plum2")

```

