\documentclass[11pt]{article}
\usepackage[fleqn]{amsmath}

\usepackage{setspace}
\usepackage[top=1in, bottom=1in, left=1in, right=1in]{geometry}
\begin{document}
\SweaveOpts{concordance=TRUE}

\begin{align}  
E[\Delta{h}] = & B_{0} + B_{1}\sqrt{h} +B_{2}(\textrm{candidate}) \qquad, \nonumber \\
\end{align}\nonumber
where $h$ is the tree height in feet and $\Delta{h}$ is annual ht growth.

 \end{document}
